version: "3.8"

services:
  api-gateway:
    build:
      context: .
      dockerfile: TechTrack.Backend/TechTrack.ApiGateway/Dockerfile
    ports:
      - "${API_GATEWAY_PORT}:8080"
    networks:
      - techtrack-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: techtrack-rabbitmq
    hostname: techtrack
    expose:
      - "5672"
    ports:
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - techtrack-network

  postgres-auth:
    image: postgres:15
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    ports:
      - "${AUTH_DB_PORT}:5432"
    networks:
      - techtrack-network

  postgres-user:
    image: postgres:15
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    ports:
      - "${USER_DB_PORT}:5432"
    networks:
      - techtrack-network

  postgres-organization:
    image: postgres:15
    environment:
      POSTGRES_DB: ${ORGANIZATION_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_organization_data:/var/lib/postgresql/data
    ports:
      - "${ORGANIZATION_DB_PORT}:5432"
    networks:
      - techtrack-network

  postgres-maintenance:
    image: postgres:15
    environment:
      POSTGRES_DB: ${MAINTENANCE_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_maintenance_data:/var/lib/postgresql/data
    ports:
      - "${MAINTENANCE_DB_PORT}:5432"
    networks:
      - techtrack-network

  postgres-notification:
    image: postgres:15
    environment:
      POSTGRES_DB: ${NOTIFICATION_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_notification_data:/var/lib/postgresql/data
    ports:
      - "${NOTIFICATION_DB_PORT}:5432"
    networks:
      - techtrack-network

  organization-service:
    build:
      context: .
      dockerfile: TechTrack.Backend/TechTrack.OrganizationService/Dockerfile
    expose:
      - "8080"
      - "8081"
    environment:
      ConnectionStrings__OrganizationServiceDbConnection: Host=postgres-organization;Database=${ORGANIZATION_DB_NAME};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__AccessTokenKey: ${JWT_ACCESS_TOKEN_KEY}
    depends_on:
      - postgres-organization
      - rabbitmq
      - api-gateway
    networks:
      - techtrack-network

  auth-service:
    build:
      context: .
      dockerfile: TechTrack.Backend/TechTrack.AuthService/Dockerfile
    expose:
      - "8080"
      - "8081"
    environment:
      ConnectionStrings__AuthServiceDbConnection: Host=postgres-auth;Database=${AUTH_DB_NAME};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      Jwt__Issuer: ${JWT_ISSUER}
    depends_on:
      - postgres-auth
      - rabbitmq
      - api-gateway
    networks:
      - techtrack-network

  user-service:
    build:
      context: .
      dockerfile: TechTrack.Backend/TechTrack.UserService/Dockerfile
    expose:
      - "8080"
      - "8081"
    environment:
      ConnectionStrings__UserServiceDbConnection: Host=postgres-user;Database=${USER_DB_NAME};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__AccessTokenKey: ${JWT_ACCESS_TOKEN_KEY}
    depends_on:
      - postgres-user
      - rabbitmq
      - api-gateway
    networks:
      - techtrack-network

  maintenance-service:
    build:
      context: .
      dockerfile: TechTrack.Backend/TechTrack.MaintenanceService/Dockerfile
    expose:
      - "8080"
      - "8081"
    environment:
      ConnectionStrings__MaintenanceServiceDbConnection: Host=postgres-maintenance;Database=${MAINTENANCE_DB_NAME};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      ConnectionStrings__Redis: redis-maintenance:6379
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__AccessTokenKey: ${JWT_ACCESS_TOKEN_KEY}
    depends_on:
      - postgres-maintenance
      - rabbitmq
      - api-gateway
    networks:
      - techtrack-network

  notification-service:
    build:
      context: .
      dockerfile: TechTrack.Backend/TechTrack.NotificationService/Dockerfile
    expose:
      - "8080"
      - "8081"
    environment:
      ConnectionStrings__NotificationServiceDbConnection: Host=postgres-notification;Database=${NOTIFICATION_DB_NAME};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__AccessTokenKey: ${JWT_ACCESS_TOKEN_KEY}
    depends_on:
      - postgres-notification
      - rabbitmq
      - api-gateway
    networks:
      - techtrack-network

  frontend:
    build:
      context: TechTrack.Frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:3000"
    volumes:
      - frontend_data:/var/lib/frontend/data
    networks:
      - techtrack-network

  redis-maintenance:
    image: redis:7
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - techtrack-network

networks:
  techtrack-network:
    driver: bridge

volumes:
  frontend_data:
  postgres_auth_data:
  postgres_user_data:
  postgres_organization_data:
  postgres_maintenance_data:
  postgres_notification_data:
  rabbitmq_data:
