version: '3.8'
services:
  api-gateway:
    build:
      context: .
      dockerfile: TechTrack.Backend/TechTrack.ApiGateway/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - techtrack-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: techtrack-rabbitmq
    hostname: techtrack
    expose:
      - "5672"
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - techtrack-network


  postgres-auth:
    image: postgres:15
    environment:
      POSTGRES_DB: auth_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - techtrack-network

  postgres-user:
    image: postgres:15
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - techtrack-network

  postgres-organization:
    image: postgres:15
    environment:
      POSTGRES_DB: organization_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_organization_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - techtrack-network
  
  postgres-maintenance:
    image: postgres:15
    environment:
      POSTGRES_DB: maintenance_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_maintenance_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - techtrack-network

  postgres-notification:
    image: postgres:15
    environment:
      POSTGRES_DB: notification_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_notification_data:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    networks:
      - techtrack-network

  organization-service:
    build:
      context: .
      dockerfile: TechTrack.Backend/TechTrack.OrganizationService/Dockerfile
    expose:
      - "8080"
      - "8081"
    environment:
      - ConnectionStrings__OrganizationServiceDbConnection=Host=postgres-organization;Database=organization_service;Username=postgres;Password=admin
      - Jwt__AccessTokenKey=5c6dd372771c07a19980ce9ad6f251f3ea8f9974a85a943152a68906a2708f7d
      - Jwt__Issuer=http://auth-service
    networks:
      - techtrack-network
    depends_on:
      - postgres-organization
      - rabbitmq
      - api-gateway

  auth-service:
    build:
      context: .
      dockerfile: TechTrack.Backend/TechTrack.AuthService/Dockerfile
    expose:
      - "8080" # REST(HTTP/1.1)
      - "8081" # gRPC(HTTP/2)
    environment:
      - ConnectionStrings__AuthServiceDbConnection=Host=postgres-auth;Database=auth_service;Username=postgres;Password=admin
      - Jwt__Issuer=http://auth-service:8080
    networks:
      - techtrack-network
    depends_on:
      - postgres-auth
      - rabbitmq
      - api-gateway

  user-service:
    build:
      context: .
      dockerfile: TechTrack.Backend/TechTrack.UserService/Dockerfile
    expose:
      - "8080"
      - "8081"
    environment:
      - ConnectionStrings__UserServiceDbConnection=Host=postgres-user;Database=user_service;Username=postgres;Password=admin
      - Jwt__Issuer=http://auth-service:8080
      - Jwt__AccessTokenKey=5c6dd372771c07a19980ce9ad6f251f3ea8f9974a85a943152a68906a2708f7d
    networks:
      - techtrack-network
    depends_on:
      - postgres-user
      - rabbitmq
      - api-gateway

  maintenance-service:
    build:
      context: .
      dockerfile: TechTrack.Backend/TechTrack.MaintenanceService/Dockerfile
    expose:
      - "8080"
      - "8081"
    environment:
      - ConnectionStrings__MaintenanceServiceDbConnection=Host=postgres-maintenance;Database=maintenance_service;Username=postgres;Password=admin
      - ConnectionStrings__Redis=redis-maintenance:6379
      - Jwt__Issuer=http://auth-service:8080
      - Jwt__AccessTokenKey=5c6dd372771c07a19980ce9ad6f251f3ea8f9974a85a943152a68906a2708f7d
    networks:
      - techtrack-network
    depends_on:
      - postgres-maintenance
      - rabbitmq
      - api-gateway

  notification-service:
    build:
      context: .
      dockerfile: TechTrack.Backend/TechTrack.NotificationService/Dockerfile
    expose:
      - "8080"
      - "8081"
    environment:
      - ConnectionStrings__NotificationServiceDbConnection=Host=postgres-notification;Database=notification_service;Username=postgres;Password=admin
      - Jwt__Issuer=http://auth-service:8080
      - Jwt__AccessTokenKey=5c6dd372771c07a19980ce9ad6f251f3ea8f9974a85a943152a68906a2708f7d
    networks:
      - techtrack-network
    depends_on:
      - postgres-notification
      - rabbitmq
      - api-gateway

  frontend:
    build:
      context: TechTrack.Frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - frontend_data:/var/lib/frontend/data
    networks:
      - techtrack-network
    
  redis-maintenance:
    image: redis:7
    ports:
    - "6379:6379"
    networks:
      - techtrack-network

networks:
  techtrack-network:
    driver: bridge

volumes:
  frontend_data:
  postgres_auth_data:
  postgres_user_data:
  postgres_organization_data:
  postgres_maintenance_data:
  postgres_notification_data:
  rabbitmq_data:
