// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TechTrack.OrganizationService.Data;

#nullable disable

namespace TechTrack.OrganizationService.Migrations
{
    [DbContext(typeof(OrganizationServiceDbContext))]
    partial class OrganizationServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TechTrack.OrganizationService.Companies.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<Guid?>("CompanyHeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_head_id");

                    b.Property<DateTime>("ConnectedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("connected_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("TechTrack.OrganizationService.Companies.Entities.CompanyUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.HasKey("UserId", "CompanyId")
                        .HasName("pk_company_user");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_company_user_company_id");

                    b.ToTable("company_user", (string)null);
                });

            modelBuilder.Entity("TechTrack.OrganizationService.Departments.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ResponsibleUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsible_user_id");

                    b.HasKey("Id")
                        .HasName("pk_departments");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_departments_company_id");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("TechTrack.OrganizationService.Departments.Entities.DepartmentUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.HasKey("UserId", "DepartmentId")
                        .HasName("pk_department_user");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_department_user_department_id");

                    b.ToTable("department_user", (string)null);
                });

            modelBuilder.Entity("TechTrack.OrganizationService.Equipments.Entities.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CurrentStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("current_status_id");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ResponsibleUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("responsible_user_id");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serialNumber");

                    b.HasKey("Id")
                        .HasName("pk_equipments");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_equipments_department_id");

                    b.ToTable("equipments", (string)null);
                });

            modelBuilder.Entity("TechTrack.OrganizationService.UserProjections.Entities.UserProjection", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.HasKey("UserId")
                        .HasName("pk_user_projections");

                    b.ToTable("user_projections", (string)null);
                });

            modelBuilder.Entity("TechTrack.OrganizationService.Companies.Entities.CompanyUser", b =>
                {
                    b.HasOne("TechTrack.OrganizationService.Companies.Entities.Company", "Company")
                        .WithMany("UsersInfo")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_user_companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("TechTrack.OrganizationService.Departments.Entities.Department", b =>
                {
                    b.HasOne("TechTrack.OrganizationService.Companies.Entities.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_departments_companies_company_id");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("TechTrack.OrganizationService.Departments.Entities.DepartmentUser", b =>
                {
                    b.HasOne("TechTrack.OrganizationService.Departments.Entities.Department", "Department")
                        .WithMany("DepartmentEmployees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_department_user_departments_department_id");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TechTrack.OrganizationService.Equipments.Entities.Equipment", b =>
                {
                    b.HasOne("TechTrack.OrganizationService.Departments.Entities.Department", null)
                        .WithMany("Equipments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_equipments_departments_department_id");
                });

            modelBuilder.Entity("TechTrack.OrganizationService.Companies.Entities.Company", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("UsersInfo");
                });

            modelBuilder.Entity("TechTrack.OrganizationService.Departments.Entities.Department", b =>
                {
                    b.Navigation("DepartmentEmployees");

                    b.Navigation("Equipments");
                });
#pragma warning restore 612, 618
        }
    }
}
